ARG BASE_IMAGE=osrf/ros:humble-desktop
FROM ${BASE_IMAGE}

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends pulseaudio-utils \
    && rm -rf /var/lib/apt/lists/*
